"""Public API for the layered tool-topology MVP."""

from .capability import (
    CapabilityResolution,
    CapabilityResolver,
    FakeCapabilityResolver,
)
from .core import (
    CapabilityResolutionError,
    DuplicateLayerError,
    DuplicateToolError,
    FastRegressionError,
    InvalidCapabilityError,
    InvalidTopologyReferenceError,
    Layer,
    LayerNotFoundError,
    RegistrationError,
    RouteSearchError,
    RouteValidationError,
    ScenarioError,
    ScenarioLoadError,
    ScenarioValidationError,
    ToolNode,
    ToolNotFoundError,
    TopologyBuildError,
    TopologyFrameworkError,
)
from .decorators import tool
from .registry import CapabilityRegistry, LayerRegistry, ToolRegistry
from .regression import (
    CandidateRoute,
    CategoryCoverage,
    CoverageAnalyzer,
    CoverageAnalyzerError,
    CoverageReport,
    CoverageResult,
    CoverageStatus,
    FailureReason,
    FastRegressionResult,
    FastRegressionRunner,
    GapEntry,
    RouteSearch,
    RouteSearcher,
    TopologyGapEntry,
)
from .route import RouteLayer, RoutePlan
from .scenario import Scenario, ScenarioLoader, ScenarioSuite
from .topology import ToolEdge, Topology, TopologyBuilder, TopologyValidationWarning

__all__ = [
    "CapabilityResolution",
    "CapabilityResolutionError",
    "CapabilityResolver",
    "CapabilityRegistry",
    "CandidateRoute",
    "CategoryCoverage",
    "CoverageAnalyzer",
    "CoverageAnalyzerError",
    "CoverageReport",
    "CoverageResult",
    "CoverageStatus",
    "DuplicateLayerError",
    "DuplicateToolError",
    "FailureReason",
    "FakeCapabilityResolver",
    "FastRegressionError",
    "FastRegressionResult",
    "FastRegressionRunner",
    "GapEntry",
    "InvalidCapabilityError",
    "InvalidTopologyReferenceError",
    "Layer",
    "LayerNotFoundError",
    "LayerRegistry",
    "RegistrationError",
    "RouteLayer",
    "RoutePlan",
    "RouteSearch",
    "RouteSearcher",
    "RouteSearchError",
    "RouteValidationError",
    "Scenario",
    "ScenarioError",
    "ScenarioLoadError",
    "ScenarioLoader",
    "ScenarioSuite",
    "ScenarioValidationError",
    "ToolEdge",
    "ToolNode",
    "ToolNotFoundError",
    "ToolRegistry",
    "Topology",
    "TopologyBuildError",
    "TopologyBuilder",
    "TopologyFrameworkError",
    "TopologyGapEntry",
    "TopologyValidationWarning",
    "tool",
]
